### ISSUE TITLE
Update contact information on home page

### ISSUE THREAD

**Issue by sp-eldata** [ElucidataInc/elucidatainc.github.io#2]
It should have Cambridge address & info@elucidata.io email ID.

**Comment by aj-eluc** [comment]
@sp-eldata : The mail address "info@elucidata.io" is already mentioned under support .
![capture](https://user-images.githubusercontent.com/32356943/30968816-282db318-a47e-11e7-9112-db94743d3089.PNG)

**Comment by sahil21** [comment]
@sp-eldata @aj-eluc  But we decided to use elmaven@elucidata.io, right?

**Comment by aj-eluc** [comment]
@Raghavdata  Check , info@elucidata.io link used under "contact us"

**Comment by Raghavdata** [comment]
I think the address seems a bit in excess. info@elucidata.io seems perfect.
