### ISSUE TITLE
Developer manual link not working

### ISSUE THREAD

**Issue by sp-eldata** [ElucidataInc/elucidatainc.github.io#4]
On the home page. Redirects to the home page again.

**Comment by aj-eluc** [comment]
@Raghavdata  check

**Comment by Raghavdata** [comment]
@aj-eluc I think the best link would be this - https://github.com/ElucidataInc/ElMaven/blob/develop/CONTRIBUTING.md

**Comment by aj-eluc** [comment]
ok , noted  .

Under "Manuals" tab on the elmaven's website , the button "developer manual
" linked to  " https://github.com/ElucidataInc/ElMaven " . That is the link
i used .

Shall i change that link as well , to the one mentioned by you?

**Comment by Raghavdata** [comment]
Yup

**Comment by aj-eluc** [comment]
done , updated both links @Raghavdata
